project_name_override: ksef

field_prefix: attr_
use_path_prefixes_for_title_model_names: True
post_hooks: []
http_timeout: 5

tag_override:
    Aktywne sesje: sessions
    Certyfikaty: certificates
    Certyfikaty klucza publicznego: publickey
    Dane testowe: testdata
    Limity i ograniczenia: limits
    Nadawanie uprawnień: permissions
    Odbieranie uprawnień: permissions
    Operacje: operations
    Pobieranie faktur: invoices
    Status wysyłki i UPO: status
    Tokeny KSeF: tokens
    Usługi Peppol: peppol
    Uzyskiwanie dostępu: auth
    Wysyłka interaktywna: sendonline
    Wysyłka wsadowa: sendbatch
    Wyszukiwanie nadanych uprawnień: permissions
